# Funding links for this project

custom:
  - https://ko-fi.com/secludedly
  - https://bit.ly/3lOXg7l
  - https://venmo.com/u/SecSteve
  - https://cash.app/$Secludedly
  - https://lh3.googleusercontent.com/d/12hKynIu6LgUCxdAdSelkjFz-rp2ZFauI=w1000?authuser=0
